-- Script para agregar datos opcionales de ubicacion a sucursales
-- Base esperada del proyecto: qr_tienda_cerrada
-- IMPORTANTE: este CSV trae links de Google Maps, pero no trae latitud/longitud.
-- Por eso este script guarda la referencia y deja latitud/longitud en NULL.
-- Para que funcione el calculo automatico por distancia, hay que llenar latitud y longitud.

USE qr_tienda_cerrada;

ALTER TABLE sucursales
  ADD COLUMN branch_number INT DEFAULT NULL AFTER id,
  ADD COLUMN nombre_referencia_ubicacion VARCHAR(255) DEFAULT NULL AFTER usuario_soporte360,
  ADD COLUMN municipio VARCHAR(255) DEFAULT NULL AFTER nombre_referencia_ubicacion,
  ADD COLUMN maps_url TEXT DEFAULT NULL AFTER municipio,
  ADD COLUMN latitud DECIMAL(10,8) DEFAULT NULL AFTER maps_url,
  ADD COLUMN longitud DECIMAL(11,8) DEFAULT NULL AFTER latitud,
  ADD COLUMN ubicacion_activa TINYINT(1) DEFAULT 0 AFTER longitud;

-- Si el ALTER anterior ya fue ejecutado antes, no lo vuelvas a ejecutar. Ejecuta solo los UPDATE.

UPDATE sucursales SET branch_number = 1, nombre_referencia_ubicacion = 'Abastos', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/dDL8HcPvFxK6qACQ6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 1;
UPDATE sucursales SET branch_number = 2, nombre_referencia_ubicacion = 'Carrillo', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/b5We3ZAkcW82Sybf7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 2;
UPDATE sucursales SET branch_number = 3, nombre_referencia_ubicacion = 'Sauces', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/3vo2RKxqXxsdKdQ97', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 3;
UPDATE sucursales SET branch_number = 4, nombre_referencia_ubicacion = 'Presidentes', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/mR3859iWoC9uupyp7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 4;
UPDATE sucursales SET branch_number = 5, nombre_referencia_ubicacion = 'San Roque', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/4XjjshWSaiJ68kgs9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 5;
UPDATE sucursales SET branch_number = 6, nombre_referencia_ubicacion = 'Satelite', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/MafEGGf2djKBkGaQ9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 6;
UPDATE sucursales SET branch_number = 7, nombre_referencia_ubicacion = 'Plazas del Sol', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/QqZpuiaZXJYfwE1UA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 7;
UPDATE sucursales SET branch_number = 8, nombre_referencia_ubicacion = 'Pie de la cuesta 1', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/ZVNMPNjGwLtaGLPm8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 8;
UPDATE sucursales SET branch_number = 9, nombre_referencia_ubicacion = 'Lomas del Marqués', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/69996JWu3QjMkZDV6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 9;
UPDATE sucursales SET branch_number = 10, nombre_referencia_ubicacion = 'Cerrito Colorado', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/baKpvGL4bEnM7q137', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 10;
UPDATE sucursales SET branch_number = 11, nombre_referencia_ubicacion = 'Andadores', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/yECTzBpzXZLsntJo9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 11;
UPDATE sucursales SET branch_number = 12, nombre_referencia_ubicacion = 'Reforma Agraria', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/ircjPvYJHqRCNGSMA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 12;
UPDATE sucursales SET branch_number = 13, nombre_referencia_ubicacion = 'Tintero 1', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/ZJ6s1dD7izuuSY4N8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 13;
UPDATE sucursales SET branch_number = 14, nombre_referencia_ubicacion = 'Tejeda 1', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/ks24XL6kT1umV7st6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 14;
UPDATE sucursales SET branch_number = 15, nombre_referencia_ubicacion = 'Satelite 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/H1NvfVg7qkKN1hV28', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 15;
UPDATE sucursales SET branch_number = 16, nombre_referencia_ubicacion = 'Ensueño', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/VmGVPMG5bRRcWDBB8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 16;
UPDATE sucursales SET branch_number = 17, nombre_referencia_ubicacion = 'Candiles 1', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/uuEfC5axWFDUm2dn7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 17;
UPDATE sucursales SET branch_number = 18, nombre_referencia_ubicacion = 'Cerrito Colorado 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/kBJskpWz4bFGuBam9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 18;
UPDATE sucursales SET branch_number = 19, nombre_referencia_ubicacion = 'Tejeda 2', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/krc1MZEFUdvfh5426', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 19;
UPDATE sucursales SET branch_number = 20, nombre_referencia_ubicacion = 'Pie de la cuesta 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/kdT9kEyT63nPQvFE8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 20;
UPDATE sucursales SET branch_number = 21, nombre_referencia_ubicacion = 'Paseo San Miguel', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/5yJGhKBsheP3MbS59', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 21;
UPDATE sucursales SET branch_number = 22, nombre_referencia_ubicacion = 'La pradera 2', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/QxsaGmPa3vNyrtHV9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 22;
UPDATE sucursales SET branch_number = 23, nombre_referencia_ubicacion = 'Loarca', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/kh78LgTuaFy2GgCz8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 23;
UPDATE sucursales SET branch_number = 24, nombre_referencia_ubicacion = 'San Miguel de Allende 1', municipio = 'San Miguel Allende', maps_url = 'https://maps.app.goo.gl/74zSHRm1G5joSPqK8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 24;
UPDATE sucursales SET branch_number = 25, nombre_referencia_ubicacion = 'San Juan de Letrán', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/DeJxcBoyC3SuFui9A', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 25;
UPDATE sucursales SET branch_number = 26, nombre_referencia_ubicacion = 'Cerrito Colorado 3', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/RveQYBHRxpLJJefA6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 26;
UPDATE sucursales SET branch_number = 27, nombre_referencia_ubicacion = 'San Pablo', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/H45uxbaBR11HAfBe9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 27;
UPDATE sucursales SET branch_number = 28, nombre_referencia_ubicacion = 'La Pradera 1', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/5Em7mZiTPePjwAQXA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 28;
UPDATE sucursales SET branch_number = 29, nombre_referencia_ubicacion = 'Campo Militar', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/14c63nWwxGqYR9Ga8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 29;
UPDATE sucursales SET branch_number = 30, nombre_referencia_ubicacion = 'Hacienda la cruz', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/BxhxKpVpqUYbkcsc8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 30;
UPDATE sucursales SET branch_number = 31, nombre_referencia_ubicacion = 'Miranda', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/bFnrAyoYHkDD5LV18', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 31;
UPDATE sucursales SET branch_number = 32, nombre_referencia_ubicacion = 'El Mirador', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/9MYxa4wr2vwucY7x8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 32;
UPDATE sucursales SET branch_number = 33, nombre_referencia_ubicacion = 'Insurgentes', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/tYVrPLuk3pTxpUfY6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 33;
UPDATE sucursales SET branch_number = 34, nombre_referencia_ubicacion = 'Paseos del Pedregal', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/rC5UhiACmWXxUg5p7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 34;
UPDATE sucursales SET branch_number = 35, nombre_referencia_ubicacion = 'Juriquilla 1', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/M8hc3bEHBRSDExCv9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 35;
UPDATE sucursales SET branch_number = 36, nombre_referencia_ubicacion = 'Real de la Loma', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/UNGemGQEbtb62i9T9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 36;
UPDATE sucursales SET branch_number = 37, nombre_referencia_ubicacion = 'Av de la luz', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/yNwSbCQkrT9NxN8S6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 37;
UPDATE sucursales SET branch_number = 38, nombre_referencia_ubicacion = 'Viñedos', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/arZdz9vttxzzKioT9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 38;
UPDATE sucursales SET branch_number = 39, nombre_referencia_ubicacion = 'Santa María', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/JUaVamRftQzoTUURA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 39;
UPDATE sucursales SET branch_number = 40, nombre_referencia_ubicacion = 'Tintero 2 ( Ex hacienda tintero )', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/N4az5tEuZJ2ASS7y6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 40;
UPDATE sucursales SET branch_number = 41, nombre_referencia_ubicacion = 'El Refugio 1', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/VTjegxkpQNv3vrBc6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 41;
UPDATE sucursales SET branch_number = 42, nombre_referencia_ubicacion = 'Villas de Santiago', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/eZ1y3ZBj2jLbWf8v5', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 42;
UPDATE sucursales SET branch_number = 43, nombre_referencia_ubicacion = 'Ciudad del Sol', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/abfhH2QSvCeGUm6H9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 43;
UPDATE sucursales SET branch_number = 44, nombre_referencia_ubicacion = 'Milenio', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/8azbznYKAhzrz9CR7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 44;
UPDATE sucursales SET branch_number = 45, nombre_referencia_ubicacion = 'Prol Pasteur', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/x7My78cWL8gwPTNw8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 45;
UPDATE sucursales SET branch_number = 46, nombre_referencia_ubicacion = 'Sonterra', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/RAMDqLxXn1XwzNGy8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 46;
UPDATE sucursales SET branch_number = 47, nombre_referencia_ubicacion = 'Valle Diamante', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/9wkvukrBb8AYGcap8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 47;
UPDATE sucursales SET branch_number = 48, nombre_referencia_ubicacion = 'Valle de Santiago', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/5oeybsSr8Rs8oFCG9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 48;
UPDATE sucursales SET branch_number = 49, nombre_referencia_ubicacion = 'Sauces 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/JTbycfr2kFCPekdY7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 49;
UPDATE sucursales SET branch_number = 50, nombre_referencia_ubicacion = 'Vista Real', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/wb22nGFh3BUgmKMh8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 50;
UPDATE sucursales SET branch_number = 51, nombre_referencia_ubicacion = 'Los Héroes', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/PT1Nr8edBjrwSkgZ7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 51;
UPDATE sucursales SET branch_number = 52, nombre_referencia_ubicacion = 'Rincones del Marqués', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/SRoQPnVHWKLTQqUq6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 52;
UPDATE sucursales SET branch_number = 53, nombre_referencia_ubicacion = 'Puerta Verona', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/KbtKVRaZmWuXgoiP8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 53;
UPDATE sucursales SET branch_number = 54, nombre_referencia_ubicacion = 'Real Solare', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/w8Y3tmT34sUjtY119', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 54;
UPDATE sucursales SET branch_number = 55, nombre_referencia_ubicacion = 'Ciudad del Sol 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/Y1XEh6DL93ixqYCK6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 55;
UPDATE sucursales SET branch_number = 56, nombre_referencia_ubicacion = 'Santuario', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/gjsodumxetbug6Ac6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 56;
UPDATE sucursales SET branch_number = 57, nombre_referencia_ubicacion = 'Los Olvera', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/414YsCvuoxKfPbkSA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 57;
UPDATE sucursales SET branch_number = 58, nombre_referencia_ubicacion = 'Real del Bosque', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/DiVzXBEMVmb8ZYvQ9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 58;
UPDATE sucursales SET branch_number = 59, nombre_referencia_ubicacion = 'Alcanfores', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/Ty2GwUtTyMLVPgRMA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 59;
UPDATE sucursales SET branch_number = 60, nombre_referencia_ubicacion = 'San Miguel de Allende 2', municipio = 'San Miguel Allende', maps_url = 'https://maps.app.goo.gl/E4vchv9gk9RD9tgi7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 60;
UPDATE sucursales SET branch_number = 61, nombre_referencia_ubicacion = 'San Isidro', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/X3prNJoZtbVHetfH6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 61;
UPDATE sucursales SET branch_number = 62, nombre_referencia_ubicacion = 'Plaza Atelier', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/bSo43CQqGpfdr5bR7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 62;
UPDATE sucursales SET branch_number = 63, nombre_referencia_ubicacion = 'Tecnologico', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/kSTzP2X3yugh7p2a8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 63;
UPDATE sucursales SET branch_number = 64, nombre_referencia_ubicacion = 'Candiles 2', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/PPXAEfA6ZCcFyizA8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 64;
UPDATE sucursales SET branch_number = 65, nombre_referencia_ubicacion = 'El Refugio 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/k2DbbbkBgx4ENSQJ8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 65;
UPDATE sucursales SET branch_number = 66, nombre_referencia_ubicacion = 'Jacal', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/UUu4YgHaGcoJ3PC2A', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 66;
UPDATE sucursales SET branch_number = 67, nombre_referencia_ubicacion = 'Jardines de la hacienda', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/kk2uff7U9Efdypu98', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 67;
UPDATE sucursales SET branch_number = 68, nombre_referencia_ubicacion = 'Av del sol', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/7J8yCncrWhqomXrn6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 68;
UPDATE sucursales SET branch_number = 69, nombre_referencia_ubicacion = 'Plaza Candiles', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/yJduHX5EbW2EfM396', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 69;
UPDATE sucursales SET branch_number = 70, nombre_referencia_ubicacion = 'Los huertos', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/hr1x4h2PokiTnYSZ6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 70;
UPDATE sucursales SET branch_number = 71, nombre_referencia_ubicacion = 'Av Cimatario', municipio = 'Querétaro', maps_url = 'https://share.google/uWBjtvKQVwiMIcS8Y', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 71;
UPDATE sucursales SET branch_number = 72, nombre_referencia_ubicacion = 'Platón', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/UYP7qGgLkYNMAqWLA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 72;
UPDATE sucursales SET branch_number = 73, nombre_referencia_ubicacion = 'Piramides', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/VVSzuwemW3iB4Nyt9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 73;
UPDATE sucursales SET branch_number = 74, nombre_referencia_ubicacion = 'Zibata 1', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/F4pRHM6TGjvbjH5k8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 74;
UPDATE sucursales SET branch_number = 75, nombre_referencia_ubicacion = 'Juriquilla 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/Ko2ARVWhLYuNQLGz6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 75;
UPDATE sucursales SET branch_number = 76, nombre_referencia_ubicacion = 'Zakia', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/6f6bFsvzfyDPHKCEA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 76;
UPDATE sucursales SET branch_number = 77, nombre_referencia_ubicacion = 'Puerta Navarra', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/xFd4AQjVmJWXctWp8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 77;
UPDATE sucursales SET branch_number = 78, nombre_referencia_ubicacion = 'Pedro Escobedo', municipio = 'Pedro Escobedo', maps_url = 'https://maps.app.goo.gl/svrpqisjUtpWTghh8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 78;
UPDATE sucursales SET branch_number = 79, nombre_referencia_ubicacion = 'Geo plazas', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/xW9VseDQiyooSSuAA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 79;
UPDATE sucursales SET branch_number = 80, nombre_referencia_ubicacion = 'Candiles 3', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/i6GnqAkwj73UfxY48', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 80;
UPDATE sucursales SET branch_number = 81, nombre_referencia_ubicacion = 'Palmares', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/Tar4zuQRwSuMCvPq7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 81;
UPDATE sucursales SET branch_number = 82, nombre_referencia_ubicacion = 'Pedro Escobedo 2', municipio = 'Pedro Escobedo', maps_url = 'https://maps.app.goo.gl/5A8xtX7nkFeYh5Mx9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 82;
UPDATE sucursales SET branch_number = 83, nombre_referencia_ubicacion = 'Plaza Belén', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/dQUFAQrjLTSvhCD27', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 83;
UPDATE sucursales SET branch_number = 84, nombre_referencia_ubicacion = 'Fuentes de Balvanera', municipio = 'Apaseo el Grande', maps_url = 'https://maps.app.goo.gl/DGRgXZxjnRR1ZmccA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 84;
UPDATE sucursales SET branch_number = 85, nombre_referencia_ubicacion = 'El Refugio 3', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/HRfdyKWkr2qwLMuP6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 85;
UPDATE sucursales SET branch_number = 86, nombre_referencia_ubicacion = 'La Gloria', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/uA4k61Jyb8t4ZZbT6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 86;
UPDATE sucursales SET branch_number = 87, nombre_referencia_ubicacion = 'San Miguel de Allende 3', municipio = 'San Miguel Allende', maps_url = 'https://maps.app.goo.gl/roEyD489qcqVxphX8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 87;
UPDATE sucursales SET branch_number = 88, nombre_referencia_ubicacion = 'Real de San Isidro San Juan del Río', municipio = 'San Juan del Río', maps_url = 'https://maps.app.goo.gl/jH2guewiY7iMckuY9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 88;
UPDATE sucursales SET branch_number = 89, nombre_referencia_ubicacion = 'El pueblito', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/x9SQrYrhGHkRN2fWA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 89;
UPDATE sucursales SET branch_number = 90, nombre_referencia_ubicacion = 'Sombrerete', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/8RMavPazYtZ721fD7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 90;
UPDATE sucursales SET branch_number = 91, nombre_referencia_ubicacion = 'Plaza Naciones', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/oa8sQrRzQYmfaQnf7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 91;
UPDATE sucursales SET branch_number = 92, nombre_referencia_ubicacion = 'Lomas Calle 27', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/NRGg4LqKMN63ncWk6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 92;
UPDATE sucursales SET branch_number = 93, nombre_referencia_ubicacion = 'Niños Héroes', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/9XGLoij5TvDmFNVw6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 93;
UPDATE sucursales SET branch_number = 94, nombre_referencia_ubicacion = 'La negreta', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/2Dc4tTS6sZEBjmSu8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 94;
UPDATE sucursales SET branch_number = 95, nombre_referencia_ubicacion = 'Villas del Refugio', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/WntGWX7HYKnpfjX98', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 95;
UPDATE sucursales SET branch_number = 96, nombre_referencia_ubicacion = 'Zibata 2', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/ccGefjr5aoCVmj1q6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 96;
UPDATE sucursales SET branch_number = 97, nombre_referencia_ubicacion = 'San Miguel de Allende 4', municipio = 'San Miguel Allende', maps_url = 'https://maps.app.goo.gl/ZCQ3f88fYjPvdTiS9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 97;
UPDATE sucursales SET branch_number = 98, nombre_referencia_ubicacion = 'Loma Bonita', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/TeQroH5nUGpgMifDA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 98;
UPDATE sucursales SET branch_number = 99, nombre_referencia_ubicacion = 'Menchaca', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/t6SrKqvwgeHu5sPX6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 99;
UPDATE sucursales SET branch_number = 100, nombre_referencia_ubicacion = 'Burócrata', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/9CYfmxoh4osomwai6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 100;
UPDATE sucursales SET branch_number = 101, nombre_referencia_ubicacion = 'Milenio #100', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/xDKmDD2b8mWFKWNH9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 101;
UPDATE sucursales SET branch_number = 102, nombre_referencia_ubicacion = 'Lomas Calle 25', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/hRjVZijeNyCjZbbi9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 102;
UPDATE sucursales SET branch_number = 104, nombre_referencia_ubicacion = 'Privada Juriquilla', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/tvdiPUfNidutnMrz8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 104;
UPDATE sucursales SET branch_number = 105, nombre_referencia_ubicacion = 'Colinas del Sol', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/ugFwdNh8GyGwCEsd7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 105;
UPDATE sucursales SET branch_number = 106, nombre_referencia_ubicacion = 'La popular', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/C4CWeTerXud3ifcz7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 106;
UPDATE sucursales SET branch_number = 107, nombre_referencia_ubicacion = 'Santa Fe', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/o6kofCYJUb3PqcRZ7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 107;
UPDATE sucursales SET branch_number = 108, nombre_referencia_ubicacion = 'Cimatario Panteón', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/NdvDGZFCaZBktSvC9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 108;
UPDATE sucursales SET branch_number = 109, nombre_referencia_ubicacion = 'Corregidora Centro', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/2J9ymN1Kq9SfCh3v5', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 109;
UPDATE sucursales SET branch_number = 110, nombre_referencia_ubicacion = 'San Juan del Río 2 El Roble', municipio = 'San Juan del Río', maps_url = 'https://maps.app.goo.gl/Wta1bnsjFFGrbxoj7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 110;
UPDATE sucursales SET branch_number = 111, nombre_referencia_ubicacion = 'El Condado', municipio = 'Corregidora', maps_url = 'https://maps.app.goo.gl/EppaBVzNuarvKkgy5', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 111;
UPDATE sucursales SET branch_number = 112, nombre_referencia_ubicacion = 'El Rocío', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/2m4C2FxuRMaAK4USA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 112;
UPDATE sucursales SET branch_number = 113, nombre_referencia_ubicacion = 'Pueblo de Jurica', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/7sCtmi2kGVJPE3gVA', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 113;
UPDATE sucursales SET branch_number = 114, nombre_referencia_ubicacion = 'Zakia Zizana', municipio = 'El Marqués', maps_url = 'https://maps.app.goo.gl/XoSwnpnLvEpC9Pc1A', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 114;
UPDATE sucursales SET branch_number = 115, nombre_referencia_ubicacion = 'Ejido San Miguel', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/Ua1qbJ9SCdzPed297', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 115;
UPDATE sucursales SET branch_number = 116, nombre_referencia_ubicacion = 'El marqués queretano', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/CEAdCrMtAh1ZyL8C7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 116;
UPDATE sucursales SET branch_number = 117, nombre_referencia_ubicacion = 'Loarca 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/xPQsGh6BbqgM1DS79', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 117;
UPDATE sucursales SET branch_number = 118, nombre_referencia_ubicacion = 'San Jose el alto 1', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/AP52YHsMBrcLiyCh8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 118;
UPDATE sucursales SET branch_number = 119, nombre_referencia_ubicacion = 'SJR - Las Aguilas', municipio = 'San Juan del Río', maps_url = 'https://maps.app.goo.gl/zZ7az4RRtgZrrL8K8', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 119;
UPDATE sucursales SET branch_number = 120, nombre_referencia_ubicacion = 'Cd del sol - Plaza Rioma', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/jaLPxAVZFhqCQZYG7', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 120;
UPDATE sucursales SET branch_number = 121, nombre_referencia_ubicacion = 'El Salitre', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/njQ9eM4SWbVbGpS8A', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 121;
UPDATE sucursales SET branch_number = 122, nombre_referencia_ubicacion = 'Reforma Deportiva', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/vHDrnoywDfrEJMov9', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 122;
UPDATE sucursales SET branch_number = 125, nombre_referencia_ubicacion = 'Villas de Santiago 2', municipio = 'Querétaro', maps_url = 'https://maps.app.goo.gl/vAP9i83RoDvXcfus6', latitud = NULL, longitud = NULL, ubicacion_activa = 0, activa = 1 WHERE id = 125;